/* prettier-ignore */

// @ts-nocheck

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Children Routes

const IndexLazyImport = createFileRoute('/')()
const TrainLazyImport = createFileRoute('/train')()
const TestLazyImport = createFileRoute('/test')()
const SettingsLazyImport = createFileRoute('/settings')()
const DeployLazyImport = createFileRoute('/deploy')()
const ConfigureLazyImport = createFileRoute('/configure')()
const AnalyzeLazyImport = createFileRoute('/analyze')()
const TrainGuidanceLazyImport = createFileRoute('/train/guidance')()
const ConfigureTagsLazyImport = createFileRoute('/configure/tags')()
const ConfigureKnowledgeLazyImport = createFileRoute('/configure/knowledge')()
const ConfigureIntentsLazyImport = createFileRoute('/configure/intents')()
const ConfigureFlowsLazyImport = createFileRoute('/configure/flows')()

// Create/Update Routes

const IndexRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

const TrainRoute = TrainLazyImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/train').then((d) => d.Route))

const TestRoute = TestLazyImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/test').then((d) => d.Route))

const SettingsRoute = SettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings').then((d) => d.Route))

const DeployRoute = DeployLazyImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/deploy').then((d) => d.Route))

const ConfigureRoute = ConfigureLazyImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/configure').then((d) => d.Route))

const AnalyzeRoute = AnalyzeLazyImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/analyze').then((d) => d.Route))

const TrainGuidanceRoute = TrainGuidanceLazyImport.update({
  id: '/train/guidance',
  path: '/train/guidance',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/train.guidance').then((d) => d.Route))

const ConfigureTagsRoute = ConfigureTagsLazyImport.update({
  id: '/configure/tags',
  path: '/configure/tags',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/configure.tags').then((d) => d.Route))

const ConfigureKnowledgeRoute = ConfigureKnowledgeLazyImport.update({
  id: '/configure/knowledge',
  path: '/configure/knowledge',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/configure.knowledge').then((d) => d.Route))

const ConfigureIntentsRoute = ConfigureIntentsLazyImport.update({
  id: '/configure/intents',
  path: '/configure/intents',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/configure.intents').then((d) => d.Route))

const ConfigureFlowsRoute = ConfigureFlowsLazyImport.update({
  id: '/configure/flows',
  path: '/configure/flows',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/configure.flows').then((d) => d.Route))

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/configure': typeof ConfigureRoute
  '/deploy': typeof DeployRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRoute
  '/configure/flows': typeof ConfigureFlowsRoute
  '/configure/intents': typeof ConfigureIntentsRoute
  '/configure/knowledge': typeof ConfigureKnowledgeRoute
  '/configure/tags': typeof ConfigureTagsRoute
  '/train/guidance': typeof TrainGuidanceRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/configure': typeof ConfigureRoute
  '/deploy': typeof DeployRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRoute
  '/configure/flows': typeof ConfigureFlowsRoute
  '/configure/intents': typeof ConfigureIntentsRoute
  '/configure/knowledge': typeof ConfigureKnowledgeRoute
  '/configure/tags': typeof ConfigureTagsRoute
  '/train/guidance': typeof TrainGuidanceRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/configure': typeof ConfigureRoute
  '/deploy': typeof DeployRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRoute
  '/configure/flows': typeof ConfigureFlowsRoute
  '/configure/intents': typeof ConfigureIntentsRoute
  '/configure/knowledge': typeof ConfigureKnowledgeRoute
  '/configure/tags': typeof ConfigureTagsRoute
  '/train/guidance': typeof TrainGuidanceRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/configure'
    | '/deploy'
    | '/settings'
    | '/test'
    | '/train'
    | '/configure/flows'
    | '/configure/intents'
    | '/configure/knowledge'
    | '/configure/tags'
    | '/train/guidance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/configure'
    | '/deploy'
    | '/settings'
    | '/test'
    | '/train'
    | '/configure/flows'
    | '/configure/intents'
    | '/configure/knowledge'
    | '/configure/tags'
    | '/train/guidance'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/configure'
    | '/deploy'
    | '/settings'
    | '/test'
    | '/train'
    | '/configure/flows'
    | '/configure/intents'
    | '/configure/knowledge'
    | '/configure/tags'
    | '/train/guidance'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ConfigureRoute: typeof ConfigureRoute
  DeployRoute: typeof DeployRoute
  SettingsRoute: typeof SettingsRoute
  TestRoute: typeof TestRoute
  TrainRoute: typeof TrainRoute
  ConfigureFlowsRoute: typeof ConfigureFlowsRoute
  ConfigureIntentsRoute: typeof ConfigureIntentsRoute
  ConfigureKnowledgeRoute: typeof ConfigureKnowledgeRoute
  ConfigureTagsRoute: typeof ConfigureTagsRoute
  TrainGuidanceRoute: typeof TrainGuidanceRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AnalyzeRoute,
  ConfigureRoute,
  DeployRoute,
  SettingsRoute,
  TestRoute,
  TrainRoute,
  ConfigureFlowsRoute,
  ConfigureIntentsRoute,
  ConfigureKnowledgeRoute,
  ConfigureTagsRoute,
  TrainGuidanceRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
