/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TestRouteImport } from './routes/test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainGuidanceRouteImport } from './routes/train.guidance'
import { Route as ConfigureTagsRouteImport } from './routes/configure.tags'
import { Route as ConfigureKnowledgeRouteImport } from './routes/configure.knowledge'
import { Route as ConfigureIntentsRouteImport } from './routes/configure.intents'
import { Route as ConfigureFlowsRouteImport } from './routes/configure.flows'

const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainGuidanceRoute = TrainGuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => TrainRoute,
} as any)
const ConfigureTagsRoute = ConfigureTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ConfigureRoute,
} as any)
const ConfigureKnowledgeRoute = ConfigureKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ConfigureRoute,
} as any)
const ConfigureIntentsRoute = ConfigureIntentsRouteImport.update({
  id: '/intents',
  path: '/intents',
  getParentRoute: () => ConfigureRoute,
} as any)
const ConfigureFlowsRoute = ConfigureFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => ConfigureRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/configure': typeof ConfigureRouteWithChildren
  '/deploy': typeof DeployRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRouteWithChildren
  '/configure/flows': typeof ConfigureFlowsRoute
  '/configure/intents': typeof ConfigureIntentsRoute
  '/configure/knowledge': typeof ConfigureKnowledgeRoute
  '/configure/tags': typeof ConfigureTagsRoute
  '/train/guidance': typeof TrainGuidanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/configure': typeof ConfigureRouteWithChildren
  '/deploy': typeof DeployRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRouteWithChildren
  '/configure/flows': typeof ConfigureFlowsRoute
  '/configure/intents': typeof ConfigureIntentsRoute
  '/configure/knowledge': typeof ConfigureKnowledgeRoute
  '/configure/tags': typeof ConfigureTagsRoute
  '/train/guidance': typeof TrainGuidanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/configure': typeof ConfigureRouteWithChildren
  '/deploy': typeof DeployRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRouteWithChildren
  '/configure/flows': typeof ConfigureFlowsRoute
  '/configure/intents': typeof ConfigureIntentsRoute
  '/configure/knowledge': typeof ConfigureKnowledgeRoute
  '/configure/tags': typeof ConfigureTagsRoute
  '/train/guidance': typeof TrainGuidanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/configure'
    | '/deploy'
    | '/settings'
    | '/test'
    | '/train'
    | '/configure/flows'
    | '/configure/intents'
    | '/configure/knowledge'
    | '/configure/tags'
    | '/train/guidance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/configure'
    | '/deploy'
    | '/settings'
    | '/test'
    | '/train'
    | '/configure/flows'
    | '/configure/intents'
    | '/configure/knowledge'
    | '/configure/tags'
    | '/train/guidance'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/configure'
    | '/deploy'
    | '/settings'
    | '/test'
    | '/train'
    | '/configure/flows'
    | '/configure/intents'
    | '/configure/knowledge'
    | '/configure/tags'
    | '/train/guidance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ConfigureRoute: typeof ConfigureRouteWithChildren
  DeployRoute: typeof DeployRoute
  SettingsRoute: typeof SettingsRoute
  TestRoute: typeof TestRoute
  TrainRoute: typeof TrainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/guidance': {
      id: '/train/guidance'
      path: '/guidance'
      fullPath: '/train/guidance'
      preLoaderRoute: typeof TrainGuidanceRouteImport
      parentRoute: typeof TrainRoute
    }
    '/configure/tags': {
      id: '/configure/tags'
      path: '/tags'
      fullPath: '/configure/tags'
      preLoaderRoute: typeof ConfigureTagsRouteImport
      parentRoute: typeof ConfigureRoute
    }
    '/configure/knowledge': {
      id: '/configure/knowledge'
      path: '/knowledge'
      fullPath: '/configure/knowledge'
      preLoaderRoute: typeof ConfigureKnowledgeRouteImport
      parentRoute: typeof ConfigureRoute
    }
    '/configure/intents': {
      id: '/configure/intents'
      path: '/intents'
      fullPath: '/configure/intents'
      preLoaderRoute: typeof ConfigureIntentsRouteImport
      parentRoute: typeof ConfigureRoute
    }
    '/configure/flows': {
      id: '/configure/flows'
      path: '/flows'
      fullPath: '/configure/flows'
      preLoaderRoute: typeof ConfigureFlowsRouteImport
      parentRoute: typeof ConfigureRoute
    }
  }
}

interface ConfigureRouteChildren {
  ConfigureFlowsRoute: typeof ConfigureFlowsRoute
  ConfigureIntentsRoute: typeof ConfigureIntentsRoute
  ConfigureKnowledgeRoute: typeof ConfigureKnowledgeRoute
  ConfigureTagsRoute: typeof ConfigureTagsRoute
}

const ConfigureRouteChildren: ConfigureRouteChildren = {
  ConfigureFlowsRoute: ConfigureFlowsRoute,
  ConfigureIntentsRoute: ConfigureIntentsRoute,
  ConfigureKnowledgeRoute: ConfigureKnowledgeRoute,
  ConfigureTagsRoute: ConfigureTagsRoute,
}

const ConfigureRouteWithChildren = ConfigureRoute._addFileChildren(
  ConfigureRouteChildren,
)

interface TrainRouteChildren {
  TrainGuidanceRoute: typeof TrainGuidanceRoute
}

const TrainRouteChildren: TrainRouteChildren = {
  TrainGuidanceRoute: TrainGuidanceRoute,
}

const TrainRouteWithChildren = TrainRoute._addFileChildren(TrainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ConfigureRoute: ConfigureRouteWithChildren,
  DeployRoute: DeployRoute,
  SettingsRoute: SettingsRoute,
  TestRoute: TestRoute,
  TrainRoute: TrainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
